# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title:            'Music Archives & Historical Resources'
description:      'Resources about music for journalists, academics, musicians, and fans. Archives, historical collections, community projects, file dumps and more.'
url:              'https://studies.laurentfintoni.com'
baseurl:          '/mji'
copyright:        ''
logo:             '/assets/mji_invert_logo.png'
default_thumb:    '/assets/mji_invert_logo.png'

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

permalink: 'pretty'
sass:
  style: compressed
exclude: ["Gemfile*", "*.gemspec", "Rakefile", "vendor", "spec", "README.md", "LICENSE.txt", "Docker*"]
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false

# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  music_history: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'mji_item' # the layout for the pages to use
    metadata:
      source: 'music_history.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/music_history' # path to the directory of images within `_data`

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: '/search/index.json' # file the index will get written to
    collections:
      music_history:
        content: false # whether or not to index page content
        fields: # the metadata fields to index
          - label
          - primary_subject
          - secondary_subjects
          - desription

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: 'About'
    link: '/about/'
  - label: 'Categories'
    sub:
      - label: 'Classical'
        link: '/classical/'
      - label: 'Country, Folk, Blues'
        link: '/country_folk_blues/'
      - label: 'Electronic Music'
        link: '/electronic_music/'
      - label: 'Hip-Hop'
        link: '/hip_hop/'
      - label: 'Jazz'
        link: '/jazz/'
      - label: 'LGBTQIA+'
        link: '/lgbtqia/'
      - label: 'Music Publications'
        link: '/music_publications/'
      - label: 'Place Specific'
        link: '/place_specific/'
      - label: 'Popular Music'
        link: '/popular_music/'
      - label: 'Punk, Hardcore, Metal'
        link: '/punk_hardcore_metal/'
      - label: 'Recorded Music'
        link: '/recorded_music/'
      - label: 'Recording Industry'
        link: '/recording_industry/'
      - label: 'Reggae, Dancehall'
        link: '/reggae_dancehall/'
      - label: 'Rock'
        link: '/rock/'
      - label: 'Soul, Funk'
        link: '/soul_funk/'
      - label: 'Sound Art, Experimental'
        link: '/sound_art_experimental/'
  - label: 'Browse'
    link: '/collection/'
  - label: 'Search'
    link: '/search/'

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer:
  links:
    - label: 'GitHub'
      link: 'https://github.com/laurentfintoni/mji_archive_resources'
    - label: 'About'
      link: '/about'
    - label: Laurent Fintoni
      link: 'https://www.laurentfintoni.com/'
    - label: Todd L. Burns
      link: 'https://www.toddlburns.com/'
  logos:
    - img: '/img/mji_logo.png'

# FIN
